### ISSUE TITLE
Review WireNode and MeterNode

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#395]
From https://github.com/phetsims/wave-interference/issues/24, I recently generalized and migrated WireNode and MeterNode from Wave Interference to scenery-phet, for reuse in other simulations.

http://localhost/scenery-phet/scenery-phet_en.html?brand=phet&ea&screens=3&component=MeterNode coded in ComponentsScreenView.demoMeterNode (which should also be reviewed) demonstrates how they can be used together.

@ariel-phet can you please recommend a reviewer?

**Comment by ariel-phet** [comment]
Thinking @pixelzoom might be a good candidate here (lots of his sims have had meters). Might be good to have a younger dev "ride along", such as @chrisklus

**Comment by ariel-phet** [comment]
@pixelzoom if not up for this, just assign back to me.

**Comment by pixelzoom** [comment]
Happy to review. @ariel-phet @samreid priority?  

> Might be good to have a younger dev "ride along", such as @chrisklus

There's less than 200 lines of code here, so this is going to be super quick. Happy to defer and do it with @chrisklus, but I'm not sure how much he'll get out of it.  Might be better to have him tag along on a more significant code review, like for an entire sim.  Let me know...

**Comment by samreid** [comment]
From my perspective, finishing within two weeks would be great.

**Comment by pixelzoom** [comment]
WireNode looks great.  But this is not what I expected to find for `MeterNode`.  `MeterNode` is currently just the meter body - it has no responsibility for creating the probes, wires, what's shown on the body, etc.  It's up to the client to create the probes and wires, and hook everything up.   So I would:

(1) Rename `MeterNode` to `MeterBodyNode`
(2) Investigate how to implement a `MeterNode` that whose responsibility is connecting and managing the parts of the meter.

**Comment by samreid** [comment]
> MeterNode is currently just the meter body

Not exactly, the MeterNode accepts the `backgroundNode` as its first parameter.  The MeterNode is more a container that provides hooks for toolbox support, and aligning probes.

I designed MeterNode like this so it is fully customizable.   For instance, the example in ComponentsScreenView shows how to create any kind of probe (in this case, a ProbeNode), and attach with a WireNode.  Moving this behavior to MeterNode would prevent us from being able to use arbitrary subtypes of ProbeNode or WireNode.  The code to add a WireNode is not complicated, and is fully general:

```js
    // Add the wire behind the probe.
    meterNode.addChild( new WireNode(
      // Connect to the meter body at the left center
      new NodeProperty( backgroundNode, 'bounds', 'leftCenter' ),
      new Property( new Vector2( -NORMAL_DISTANCE, 0 ) ),

      // Connect to the probe at the center bottom
      new NodeProperty( probeNode, 'bounds', 'centerBottom' ),
      new Property( new Vector2( 0, NORMAL_DISTANCE ) ), {
        lineWidth: 3,
        stroke: 'black'
      }
    ) );
```

I don't see an appropriate way to move this functionality into MeterNode without significantly hampering its generality.

**Comment by pixelzoom** [comment]
I'm fine with what you've described above. But `MeterNode` is not a meter -- it's the meter body only.  

What is `synchronizeProbeLocations`? It's `@private`, it's documentation looks suspect, and it forces the first drag to always drag both the probes with the body -- which is not necessarily desirable in general, only if dragging from a toolbox.

**Comment by samreid** [comment]
In the preceding commit, I revised the documentation and defaulted `synchronizeProbeLocations` to false.  Now it only gets set to true when `startDrag` is called, which is only called when dragging out of a toolbox.  Do you think this will be sufficient, or do you think MeterNode needs another way for clients to set `synchronizeProbeLocations` to `true`?

**Comment by pixelzoom** [comment]
Why do you need `synchronizeProbeLocations` at all? Why doesn't `startDrag` just call `alignProbes`?

**Comment by samreid** [comment]
The probes need to remain aligned during the drag, see this part:

```js
      drag: function() {
        if ( self.synchronizeProbeLocations ) {
          self.alignProbes();
        }
      },
``` 

I'll try to document that better, stay tuned for a commit.

**Comment by pixelzoom** [comment]
`MeterNode`, as implemented, really has nothing to do with probes.  It has things like `alignProbesEmitter` and `alignProbes`, but the role of those things is to generally tell something else that the meter body has moved, and that anything related to the meter body should also be moved.     So my opinion is that this is not the "meter" but the "meter body" only, and should therefore be renamed `MeterBodyNode`.  And in clients like `WAVE_INTERFERENCE/WaveMeterNode`, it would be more appropriate to use `MeterBodyNode` via composition, not inheritance as is currently done.

Having `MeterBodyNode` and `WireNode` is a good first step, so that clients can compose their own meters.  But I think that there is likely to be some boilerplate code related to putting those pieces (along with probes) together into a "meter".   I'm OK with not investigating that now, if now is not the right time to put the effort into that.

**Comment by pixelzoom** [comment]
Some buggy/vestigial doc that appears in MeterNode:

```
30 // This function is called when the a wave detector drag ends.
40 // should not be children if the backgroundNode if they need to translate independently
80 * Put the probes into their standard position relative to the graph body.

**Comment by samreid** [comment]
After simplification, MeterNode was only providing trivial functionality which seemed better addressed in the client.  Therefore MeterNode has been deleted.  Back to @pixelzoom for review/discussion.

**Comment by pixelzoom** [comment]
> I renamed MeterNode => MeterBodyNode.

> After simplification, MeterNode was only providing trivial functionality which seemed better addressed in the client. Therefore MeterNode has been deleted.

I'm confused.  Did you delete MeterNode or MeterBodyNode?  I still see MeterBodyNode in scenery-phet master.

**Comment by samreid** [comment]
First it was renamed to MeterBodyNode, then MeterBodyNode was deleted.  It looks like I neglected to push that commit, my apologies.

**Comment by samreid** [comment]
I pushed a minor change for the scenery-phet demo in https://github.com/phetsims/scenery-phet/commit/fcfa829b7c160affebebdb0d1f239a77b861aae3

Have you reviewed `demoWireNode` in ComponentsScreenView?  If that checks out, I think we can close the issue.

**Comment by pixelzoom** [comment]
WireNode demo reviewed. Closing.

**Comment by pixelzoom** [comment]
Reopening.  Two things after playing with the WireNode demo some more:

(1) WireNode should have a default stroke, since we don't want to create an invisible WireNode by default.  See first commit above.

(2) Simplify the WireNode demo (demoWireNode in ComponentsScreenView) to highlight WireNode.  I took a stab at this in the second commit above.  If you prefer the more complicated demo, feel free to revert.

**Comment by samreid** [comment]
Those changes look great, thanks, closing.
