### ISSUE TITLE
Delete ResetAllButtonIO

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#572]
From https://github.com/phetsims/studio/issues/35, we no longer need it, and perhaps deleting it is the best way to go. This also relates to https://github.com/phetsims/sun/issues/558

**Comment by zepumph** [comment]
Done above. @chrisklus please review. As a reminder this was no longer needed because of our new logic in the ResetAllButton (moved/refactored from studio originally which used ResetAllButtonIO).

**Comment by chrisklus** [comment]
Looks great, thanks! I still see a couple usages in cck but it seems like those files maybe aren't supposed to exist anyway (cck-ac is not is testable-phet-io and doesn't have phet-io options in phetmarks).

Back to you @zepumph.

**Comment by zepumph** [comment]
Thanks! I discussed with @samreid and we decided to delete those files. Closing
